# Generated by Django 3.2.23 on 2023-12-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231216_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_username',
        ),
    ]
